trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:


- stage: Build
  displayName: 'Compilar e Gerar Artefato'
  jobs:
  - job: BuildJob
    steps:
    
    # 1. Compacta os arquivos gerados (sem criar a pasta /s/)
    - task: ArchiveFiles@2
      displayName: 'Compactar Aplicação'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false # Garante que os arquivos ficam na raiz do zip
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'

    # 2. Publica o .zip para o próximo estágio conseguir usar
    - task: PublishPipelineArtifact@1
      displayName: 'Publicar Artefato'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/app.zip'
        artifact: 'drop'


- stage: Deploy
  displayName: 'Deploy do Código'
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    
    # Baixa o .zip gerado no estágio de Build
    - download: current
      artifact: drop

    - task: AzureCLI@2
      displayName: 'Publicar Código no Azure App Service'
      inputs:
        azureSubscription: '8a7576c7-2b1f-464e-a096-0321e82c2c7a'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Configura o comando de inicialização do FastAPI
          az webapp config set --resource-group TesteCLI --name task-fastapi-db --startup-file "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"

          # Envia apenas o arquivo do código atualizado
          az webapp deploy --resource-group TesteCLI --name task-fastapi-db --src-path "$(Pipeline.Workspace)/drop/app.zip" --type zip